#!/usr/bin/env bash
# creating a file "/var/run/myscript.pid"
# displaying "To infinity and beyond" indefinitely
#displaying "I hate the kill command" when receiving a SIGTERM siganl
# displaying 'Y U no love me?!' when receiving  a SIGINT siganal
# deletes the file
echo $$ > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid' SIGTERM
	trap 'echo "Y U no love me ?!"' SIGINT
	trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT
done
