#!/usr/bin/env bash
# creating a file "/var/run/myscript.pid"
# displaying "To infinity and beyond" indefinitely
#displaying "I hate the kill command" when receiving a SIGTERM siganl
# displaying 'Y U no love me?!' when receiving  a SIGINT siganal
# deletes the file

trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
echo "rm /var/run/myscript.pid | kill /var/run/myscript.pid" SIGQUIT/SIGTERM
a=1
while [ $a -ge 1 ]
do
	echo 'To infinity and beyond'

